### ISSUE TITLE
Support for PHP and SQL

### ISSUE THREAD

**Issue by e-medeiros** [mariusbegby/rich-black-theme#7]
PHP some keywords are not being highlighted. 
SQL are poorly highlighted.

**Comment by mariusbegby** [comment]
Hey @e-medeiros!

Thanks for making me aware of this. I have only tested this mostly in my own commonly used languages, so some languages might be lacking a bit. I will look into PHP and SQL and improve syntax highlighting and be pushing an update when ready. I'll let you know here in this issue when it's available.

**Comment by mariusbegby** [comment]
Closing as I'm no longer working on this project.
